port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
allow-lan: true
bind-address: '*'

skip-auth-prefixes:
  - 127.0.0.1/8
  - ::1/128

ipv6: false
find-process-mode: off
log-level: info
mode: rule

external-controller: 0.0.0.0:9090
external-ui: metacubexd
external-ui-url: "https://ghfast.top/github.com/MetaCubeX/metacubexd/archive/gh-pages.zip"

unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
geodata-loader: standard
geodata-mode: true
geo-auto-update: true
geo-update-interval: 24
keep-alive-interval: 60

geox-url:
  geoip: "https://ghfast.top/github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://ghfast.top/github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://ghfast.top/github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
  asn: "https://ghfast.top/github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"

tun:
  enable: true
  stack: system # system gvisor mixed
  auto-redirect: true
  auto-route: true
  strict-route: true
  route-exclude-address-set: [cncidr, chinaips]
  auto-detect-interface: true

profile:
  store-selected: true
  store-fake-ip: true
  
dns:
  enable: true
  ipv6: true
  prefer-h3: false
  respect-rules: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip # fake-ip or redir-host
  fake-ip-range: 28.0.0.1/8
  use-hosts: true
  use-system-hosts: true
  default-nameserver:
    - quic://223.5.5.5:853
    - https://1.12.12.12/dns-query
  nameserver-policy:
    "+.lohome.top,+.syncthing.net,+.zerotier.net":
      - https://223.5.5.5/dns-query#ecs=120.76.0.0/14&ecs-override=true=h3=true
      - https://1.12.12.12/dns-query#ecs=120.76.0.0/14&ecs-override=true
    "rule-set:direct,mydirect,china,chinax,chinatest": 
      - https://223.5.5.5/dns-query#ecs=120.76.0.0/14&ecs-override=true=h3=true
      - https://1.12.12.12/dns-query#ecs=120.76.0.0/14&ecs-override=true
    "geosite:tracker,private":
      - https://223.5.5.5/dns-query#ecs=120.76.0.0/14&ecs-override=true=h3=true
      - https://1.12.12.12/dns-query#ecs=120.76.0.0/14&ecs-override=true
    "geosite:cn,tld-cn,category-games@cn,apple-cn,apple,microsoft@cn,onedrive": 
      - https://223.5.5.5/dns-query#ecs=120.76.0.0/14&ecs-override=true=h3=true
      - https://1.12.12.12/dns-query#ecs=120.76.0.0/14&ecs-override=true
    "rule-set:github,mygithub,google,gfw,proxy,tiktok,openai,myopenai,proxyclassical,global":
      - https://8.8.8.8/dns-query#ecs=120.76.0.0/14&ecs-override=true
      - https://9.9.9.12/dns-query#ecs=120.76.0.0/14&ecs-override=true
    "geosite:github,google,facebook,twitter,tiktok,openai":
      - https://8.8.8.8/dns-query#ecs=120.76.0.0/14&ecs-override=true
      - https://9.9.9.12/dns-query#ecs=120.76.0.0/14&ecs-override=true
    "rule-set:crypto,cryptocurrency,mycrypto,binance,mybinance": 
      - https://223.5.5.5/dns-query#ecs=120.76.0.0/14&ecs-override=true=h3=true
      - https://1.12.12.12/dns-query#ecs=120.76.0.0/14&ecs-override=true
  proxy-server-nameserver: 
      - https://223.5.5.5/dns-query#ecs=120.76.0.0/14&ecs-override=true=h3=true
      - https://1.12.12.12/dns-query#ecs=120.76.0.0/14&ecs-override=true
  direct-nameserver:
      - https://223.5.5.5/dns-query#ecs=120.76.0.0/14&ecs-override=true=h3=true
      - https://1.12.12.12/dns-query#ecs=120.76.0.0/14&ecs-override=true
  direct-nameserver-follow-policy: false
  nameserver:
      - https://223.5.5.5/dns-query#ecs=120.76.0.0/14&ecs-override=true=h3=true
      - https://1.12.12.12/dns-query#ecs=120.76.0.0/14&ecs-override=true
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "WORKGROUP"
    - "rule-set:direct"
    - "rule-set:mydirect"
    - "rule-set:china"
    - "rule-set:chinax"
    - "rule-set:chinatest"
    - "rule-set:private"
    - "geosite:private"
    - "geosite:cn"
    - "geosite:tld-cn"
    - "geosite:tracker"
    - "rule-set:apple"
    - "rule-set:icloud"
    - "rule-set:appleall"
    - "+.cn"
    - "+.lan"
    - "+.local"
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - stun.*.*
    - stun.*.*.*
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"

global-ua: clash.meta

NodeParam: &NodeParam {type: http, override: {udp: true, skip-cert-verify: true}, interval: 86400, health-check: {enable: true, url: 'http://connectivitycheck.platform.hicloud.com/generate_204', interval: 3600, lazy: true, timeout: 3000}}

proxy-providers: 
  cordc:
    url: 'https://sub.lohome.top/sub?target=clash&new_name=true&url=https%3A%2F%2Fwww.ccsub.online%2Flink%2FpGq7quiAtOPpW44G%3Fclash%3D1&config=https%3A%2F%2Fraw.githubusercontent.com%2FCuminLo%2Fclash-rules%2Fmaster%2FACL4SSR_Online_Full_lohome_meta.ini&scv=true&add_emoji=true&append_type=true'
    <<: *NodeParam
    path: './ProxyProvider/cordc.yaml'

RuleSetDomain: &RuleSetDomain {type: http, behavior: domain, interval: 86400, proxy: DIRECT}
RuleSetClassical: &RuleSetClassical {type: http, behavior: classical, interval: 86400, proxy: DIRECT}
RuleSetIpcidr: &RuleSetIpcidr {type: http, behavior: ipcidr, interval: 86400, proxy: DIRECT}

rule-providers:
  reject:
    <<: *RuleSetDomain
    url: "https://ghfast.top/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml

  directprocess:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/CuminLo/clash-rules/master/DirectProcess.list"
    path: ./ruleset/directprocess.yaml

  mydirect:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/CuminLo/clash-rules/master/DirectDomain.list"
    path: ./ruleset/mydirect.yaml

  myproxy:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/CuminLo/clash-rules/master/Proxy.list"
    path: ./ruleset/myproxy.yaml

  binance:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Binance/Binance_No_Resolve.yaml"
    path: ./ruleset/binance.yaml

  mybinance:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/CuminLo/clash-rules/master/Binance.list"
    path: ./ruleset/mybinance.yaml

  cryptocurrency:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cryptocurrency/Cryptocurrency.yaml"
    path: ./ruleset/cryptocurrency.yaml

  crypto:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Crypto/Crypto_No_Resolve.yaml"
    path: ./ruleset/crypto.yaml

  mycrypto:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/CuminLo/clash-rules/master/Crypto.list"
    path: ./ruleset/mycrypto.yaml

  icloud:
    <<: *RuleSetDomain
    url: "https://ghfast.top/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./ruleset/icloud.yaml

  apple:
    <<: *RuleSetDomain
    url: "https://ghfast.top/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/apple.yaml

  appleall:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Classical_No_Resolve.yaml"
    path: ./ruleset/appleall.yaml

  netflix:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix_Classical_No_Resolve.yaml"
    path: ./ruleset/netflix.yaml

  youtube:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube_No_Resolve.yaml"
    path: ./ruleset/youtube.yaml

  googleFCM:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM_No_Resolve.yaml"
    path: ./ruleset/googleFCM.yaml

  google:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google_No_Resolve.yaml"
    path: ./ruleset/google.yaml

  openai:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI_No_Resolve.yaml"
    path: ./ruleset/openai.yaml

  myopenai:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/CuminLo/clash-rules/master/AI.list"
    path: ./ruleset/myopenai.yaml

  bahamut:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut_No_Resolve.yaml"
    path: ./ruleset/bahamut.yaml

  amazon:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Amazon/Amazon_No_Resolve.yaml"
    path: ./ruleset/amazon.yaml

  onedrive:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive_No_Resolve.yaml"
    path: ./ruleset/onedrive.yaml

  microsoft:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft_No_Resolve.yaml"
    path: ./ruleset/microsoft.yaml

  discord:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Discord/Discord_No_Resolve.yaml"
    path: ./ruleset/discord.yaml

  twitter:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter_No_Resolve.yaml"
    path: ./ruleset/twitter.yaml

  tiktok:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok_No_Resolve.yaml"
    path: ./ruleset/tiktok.yaml

  mygithub:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/CuminLo/clash-rules/master/Github.list"
    format: text
    path: ./ruleset/mygithub.yaml

  github:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub_No_Resolve.yaml"
    path: ./ruleset/github.yaml

  proxy:
    <<: *RuleSetDomain
    url: "https://ghfast.top/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/proxy.yaml

  china:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_No_Resolve.yaml"
    path: ./ruleset/china.yaml

  chinax:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Classical_No_Resolve.yaml"
    path: ./ruleset/chinax.yaml

  chinatest:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaTest/ChinaTest_Classical_No_Resolve.yaml"
    path: ./ruleset/chinatest.yaml

  direct:
    <<: *RuleSetDomain
    url: "https://ghfast.top/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/direct.yaml

  private:
    <<: *RuleSetDomain
    url: "https://ghfast.top/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/private.yaml

  gfw:
    <<: *RuleSetDomain
    url: "https://ghfast.top/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"
    path: ./ruleset/gfw.yaml

  global:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Classical_No_Resolve.yaml"
    path: ./ruleset/global.yaml

  proxyclassical:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy_Classical_No_Resolve.yaml"
    path: ./ruleset/proxyclassical.yaml

  telegramcidr:
    <<: *RuleSetIpcidr
    url: "https://ghfast.top/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml

  cncidr:
    <<: *RuleSetIpcidr
    url: "https://ghfast.top/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./ruleset/cncidr.yaml

  chinaips:
    <<: *RuleSetIpcidr
    url: "https://ghfast.top/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPs/ChinaIPs_IP.yaml"
    path: ./ruleset/chinaips.yaml

  lancidr:
    <<: *RuleSetIpcidr
    url: "https://ghfast.top/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
    path: ./ruleset/lancidr.yaml

  applications:
    <<: *RuleSetClassical
    url: "https://ghfast.top/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./ruleset/applications.yaml

FilterCrypto: &FilterCrypto '^(?=.*((?i)ðŸ‡¸ðŸ‡¬|å¡|ç‹®|SG|Singapore|å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼çŽ‰|æ²ªæ—¥|æ·±æ—¥|JP))^(?!.*(ç½‘ç«™|åœ°å€|å‰©ä½™|è¿‡æœŸ|æ—¶é—´|æœ‰æ•ˆ|ç½‘å€|ç¦æ­¢|é‚®ç®±|å‘å¸ƒ|å®¢æœ|è®¢é˜…|èŠ‚ç‚¹)).*$'
FilterUS: &FilterUS '^(?=.*((?i)ðŸ‡ºðŸ‡¸|ç¾Žå›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸŽ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡ž|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|(\b(US|United States)\b)))^(?!.*(ç½‘ç«™|åœ°å€|å‰©ä½™|è¿‡æœŸ|æ—¶é—´|æœ‰æ•ˆ|ç½‘å€|ç¦æ­¢|é‚®ç®±|å‘å¸ƒ|å®¢æœ|è®¢é˜…|èŠ‚ç‚¹)).*$'
FilterHK: &FilterHK '^(?=.*((?i)æ¸¯|(\b(HK|Hong Kong)\b)))^(?!.*(ç½‘ç«™|åœ°å€|å‰©ä½™|è¿‡æœŸ|æ—¶é—´|æœ‰æ•ˆ|ç½‘å€|ç¦æ­¢|é‚®ç®±|å‘å¸ƒ|å®¢æœ|è®¢é˜…|èŠ‚ç‚¹)).*$'
FilterChat: &FilterChat '(Realityå°|tw|taiwan|Chat|GPT)'

UrlTest: &UrlTest 
  type: url-test
  url: 'http://connectivitycheck.platform.hicloud.com/generate_204'
  disable-udp: false
  hidden: false
  include-all: true
  tolerance: 100
  lazy: true
  interval: 300
  timeout: 1000
  max-failed-times: 3

SelectAll: &SelectAll 
  type: select
  disable-udp: false
  hidden: false
  include-all: true
  lazy: true
  interval: 300
  timeout: 1000
  max-failed-times: 3

Select: &Select
  type: select
  disable-udp: false
  hidden: false
  lazy: true
  interval: 300
  timeout: 1000
  max-failed-times: 3

pr: &pr {type: select, disable-udp: false, lazy: true, hidden: false, interval: 300, timeout: 1000, proxies: [ðŸ”¥ æ‰‹åŠ¨åˆ‡æ¢, ðŸš€ èŠ‚ç‚¹é€‰æ‹©, ðŸ” è½åœ°é¸¡, ðŸ‡ºðŸ‡² ç¾Žå›½èŠ‚ç‚¹, â™»ï¸ è‡ªåŠ¨é€‰æ‹©]}
twPr: &twPr {type: select, disable-udp: false, lazy: true, hidden: false, interval: 300, timeout: 1000, proxies: [ðŸ—¨ GPTèŠ‚ç‚¹, ðŸš€ èŠ‚ç‚¹é€‰æ‹©, ðŸ” è½åœ°é¸¡, ðŸ‡ºðŸ‡² ç¾Žå›½èŠ‚ç‚¹, â™»ï¸ è‡ªåŠ¨é€‰æ‹©]}
directPr: &directPr {type: select, disable-udp: false, lazy: true, hidden: false, interval: 300, timeout: 1000, proxies: [DIRECT, ðŸš€ èŠ‚ç‚¹é€‰æ‹©, ðŸ” è½åœ°é¸¡, ðŸ‡ºðŸ‡² ç¾Žå›½èŠ‚ç‚¹, â™»ï¸ è‡ªåŠ¨é€‰æ‹©]}

proxy-groups: 
  - {name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©, <<: *Select, proxies: [ðŸ”¥ æ‰‹åŠ¨åˆ‡æ¢, ðŸš è´è´äº‘, ðŸ—¨ GPTèŠ‚ç‚¹, ðŸ‡­ðŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ðŸ” è½åœ°é¸¡, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, DIRECT]}
  - {name: ðŸ”¥ æ‰‹åŠ¨åˆ‡æ¢, <<: *SelectAll}
  - {name: â³ æµ‹é€Ÿå§, <<: *SelectAll}
  - {name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©, <<: *UrlTest}
  - {name: ðŸ…±ï¸ Crypto, <<: *SelectAll, filter: *FilterCrypto}
  - {name: ðŸ†Ž AdBlock, type: select, proxies: [REJECT, DIRECT]}
  - {name: ðŸŽ è‹¹æžœæœåŠ¡, <<: *directPr}
  - {name: ðŸ‡¬ Google, <<: *pr}
  - {name: ðŸ¤– ChatæœåŠ¡, <<: *Select, proxies: [ðŸ—¨ GPTèŠ‚ç‚¹, âœˆï¸ riolu, ðŸ” è½åœ°é¸¡, ðŸ”¥ æ‰‹åŠ¨åˆ‡æ¢]}
  - {name: ðŸ“¹ æ²¹ç®¡è§†é¢‘, <<: *pr}
  - {name: ðŸ‘¨â€ðŸ’»â€ Github, <<: *pr}
  - {name: ðŸ’¬ è‡ªç”±æ¶ˆæ¯, <<: *pr}
  - {name: ðŸ“º å·´å“ˆå§†ç‰¹, <<: *twPr}
  - {name: â“‚ï¸ å¾®è½¯äº‘ç›˜, <<: *directPr}
  - {name: â“‚ï¸ å¾®è½¯æœåŠ¡, <<: *directPr}
  - {name: ðŸ” è½åœ°é¸¡, <<: *Select, use: [vps]}
  - {name: ðŸš è´è´äº‘, <<: *Select, use: [beibei]}
  - {name: âœˆï¸ riolu, <<: *Select, use: [riolu]}
  - {name: ðŸ¶ æ³¡æ³¡ç‹—, <<: *Select, use: [paopaodog]}
  - {name: ðŸ‡ºðŸ‡² ç¾Žå›½èŠ‚ç‚¹, <<: *UrlTest, filter: *FilterUS}
  - {name: ðŸ—¨ GPTèŠ‚ç‚¹, <<: *UrlTest, filter: *FilterChat}
  - {name: ðŸ‡­ðŸ‡° é¦™æ¸¯èŠ‚ç‚¹, <<: *UrlTest, filter: *FilterHK}
  - {name: ðŸŸ æ¼ç½‘ä¹‹é±¼, type: select, disable-udp: false, lazy: true, hidden: false, interval: 300, timeout: 600, proxies: [DIRECT, ðŸ‡­ðŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ðŸ‡ºðŸ‡² ç¾Žå›½èŠ‚ç‚¹, ðŸš€ èŠ‚ç‚¹é€‰æ‹©]}

rules:
  - DOMAIN-SUFFIX,ip.gs,â³ æµ‹é€Ÿå§
  - DOMAIN-SUFFIX,ip.sb,â³ æµ‹é€Ÿå§
  - DOMAIN-SUFFIX,ipino.io,â³ æµ‹é€Ÿå§
  - DOMAIN-SUFFIX,ipleak.net,â³ æµ‹é€Ÿå§
  - DOMAIN-SUFFIX,dnsleaktest.com,â³ æµ‹é€Ÿå§
  - DOMAIN-SUFFIX,ipaddress.my,â³ æµ‹é€Ÿå§
  - DOMAIN-SUFFIX,fast.com,â³ æµ‹é€Ÿå§
  - DOMAIN-SUFFIX,speedtest.net,â³ æµ‹é€Ÿå§
  - DOMAIN-SUFFIX,speedtest.frontier.com,â³ æµ‹é€Ÿå§
  - DOMAIN-SUFFIX,speedtestcustom.com,â³ æµ‹é€Ÿå§
  - DOMAIN-SUFFIX,speed.cloudflare.com,â³ æµ‹é€Ÿå§
  - RULE-SET,myproxy,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,mycrypto,ðŸ…±ï¸ Crypto
  - RULE-SET,mybinance,ðŸ…±ï¸ Crypto
  - RULE-SET,binance,ðŸ…±ï¸ Crypto
  - RULE-SET,cryptocurrency,ðŸ…±ï¸ Crypto
  - RULE-SET,crypto,ðŸ…±ï¸ Crypto
  - RULE-SET,directprocess,DIRECT
  - RULE-SET,mydirect,DIRECT
  - PROCESS-NAME,android.uid.system,ðŸ‡¬ Google
  - PROCESS-NAME,com.google.uid.shared,ðŸ‡¬ Google
  - PROCESS-NAME,com.android.vending,ðŸ‡¬ Google
  - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,ðŸ‡¬ Google
  - DOMAIN-SUFFIX,android.googleapis.com,ðŸ‡¬ Google
  - DOMAIN-SUFFIX,android.clients.google.com,ðŸ‡¬ Google
  - DOMAIN-SUFFIX,play.googleapis.com,ðŸ‡¬ Google
  - DOMAIN-SUFFIX,services.googleapis.cn,ðŸ‡¬ Google
  - DOMAIN-SUFFIX,voice.google.com,ðŸ‡¬ Google
  - DOMAIN-SUFFIX,dl.google.com,ðŸ‡¬ Google
  - IP-CIDR,224.0.0.0/4,DIRECT,no-resolve
  - IP-CIDR,103.41.167.0/24,DIRECT,no-resolve
  - IP-CIDR,74.48.160.148/32,DIRECT,no-resolve
  - RULE-SET,openai,ðŸ¤– ChatæœåŠ¡
  - RULE-SET,myopenai,ðŸ¤– ChatæœåŠ¡
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,icloud,ðŸŽ è‹¹æžœæœåŠ¡
  - RULE-SET,apple,ðŸŽ è‹¹æžœæœåŠ¡
  - RULE-SET,appleall,ðŸŽ è‹¹æžœæœåŠ¡
  - GEOSITE,apple-cn,ðŸŽ è‹¹æžœæœåŠ¡
  - RULE-SET,youtube,ðŸ“¹ æ²¹ç®¡è§†é¢‘
  - RULE-SET,netflix,ðŸ“¹ æ²¹ç®¡è§†é¢‘
  - GEOSITE,youtube,ðŸ“¹ æ²¹ç®¡è§†é¢‘
  - GEOIP,netflix,ðŸ“¹ æ²¹ç®¡è§†é¢‘
  - RULE-SET,googleFCM,ðŸ‡¬ Google
  - RULE-SET,google,ðŸ‡¬ Google
  - GEOSITE,google,ðŸ‡¬ Google
  - GEOIP,google,ðŸ‡¬ Google
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,tracker,DIRECT
  - RULE-SET,reject,ðŸ†Ž AdBlock
  - GEOSITE,category-ads-all,ðŸ†Ž AdBlock
  - RULE-SET,bahamut,ðŸ“º å·´å“ˆå§†ç‰¹
  - GEOSITE,bahamut,ðŸ“º å·´å“ˆå§†ç‰¹
  - RULE-SET,mygithub,ðŸ‘¨â€ðŸ’»â€ Github
  - RULE-SET,github,ðŸ‘¨â€ðŸ’»â€ Github
  - GEOSITE,github,ðŸ‘¨â€ðŸ’»â€ Github
  - RULE-SET,onedrive,â“‚ï¸ å¾®è½¯äº‘ç›˜
  - GEOSITE,onedrive,â“‚ï¸ å¾®è½¯äº‘ç›˜
  - RULE-SET,microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,telegramcidr,ðŸ’¬ è‡ªç”±æ¶ˆæ¯,no-resolve
  - RULE-SET,twitter,ðŸ’¬ è‡ªç”±æ¶ˆæ¯
  - RULE-SET,discord,ðŸ’¬ è‡ªç”±æ¶ˆæ¯
  - RULE-SET,tiktok,ðŸ’¬ è‡ªç”±æ¶ˆæ¯
  - GEOSITE,telegram,ðŸ’¬ è‡ªç”±æ¶ˆæ¯
  - GEOSITE,twitter,ðŸ’¬ è‡ªç”±æ¶ˆæ¯
  - GEOIP,twitter,ðŸ’¬ è‡ªç”±æ¶ˆæ¯
  - RULE-SET,gfw,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,proxy,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,global,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,proxyclassical,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,china,DIRECT
  - RULE-SET,chinax,DIRECT
  - RULE-SET,chinatest,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT,no-resolve
  - RULE-SET,cncidr,DIRECT,no-resolve
  - RULE-SET,chinaips,DIRECT,no-resolve
  - GEOIP,LAN,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,ðŸŸ æ¼ç½‘ä¹‹é±¼